### ISSUE TITLE
debugging deployment issue

### ISSUE THREAD

**Issue by critzo** [m-lab/mlab-vis-api#35]
When attempting to update the appengine service using the deploy instructions in the readme, receiving errors that need to be debugged. Posting here for reference and in case others have thoughts. Below are the error results of a recent attempt ([cloudbuilder logs](https://console.cloud.google.com/gcr/builds/afad9265-3ede-43ff-a5f0-0d764e1e5c8b?project=581276032543)):

```
...
Updating service [data-api] (this may take several minutes)...failed.          
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:
+ [[ sandbox == production ]]
+ [[ sandbox == staging ]]
+ [[ sandbox == sandbox ]]
+ source ./environments/sandbox.sh
++ BIGTABLE_INSTANCE=viz-pipeline
++ PROJECT=mlab-sandbox
++ API_MODE=sandbox
++ BIGTABLE_POOL_SIZE=10
+ BIGTABLE_CONFIG_DIR=bigtable_configs
+ BIGTABLE_INSTANCE=viz-pipeline
+ PROJECT=mlab-sandbox
+ API_MODE=sandbox
+ GOOGLE_APPLICATION_CREDENTIALS=cred.json
+ BIGTABLE_POOL_SIZE=10
+ gunicorn --timeout=1480 -b :8080 main:app
[2019-03-05 17:55:52 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2019-03-05 17:55:52 +0000] [7] [INFO] Listening at: http://0.0.0.0:8080 (7)
[2019-03-05 17:55:52 +0000] [7] [INFO] Using worker: sync
[2019-03-05 17:55:52 +0000] [11] [INFO] Booting worker with pid: 11
[2019-03-05 17:55:53 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/mlab-vis-api/main.py", line 15, in <module>
    from mlab_api.endpoints.locations import LOCATIONS_NS
  File "/mlab-vis-api/mlab_api/endpoints/locations.py", line 11, in <module>
    from mlab_api.data.data import LOCATION_DATA as DATA
  File "/mlab-vis-api/mlab_api/data/data.py", line 8, in <module>
    from mlab_api.data.location_data import LocationData
  File "/mlab-vis-api/mlab_api/data/location_data.py", line 5, in <module>
    from mlab_api.data.base_data import Data
  File "/mlab-vis-api/mlab_api/data/base_data.py", line 10, in <module>
    import mlab_api.data.bigtable_utils as bt
  File "/mlab-vis-api/mlab_api/data/bigtable_utils.py", line 11, in <module>
    from google.cloud import bigtable
  File "/env/local/lib/python2.7/site-packages/google/cloud/bigtable/__init__.py", line 21, in <module>
    from google.cloud.bigtable.client import Client
  File "/env/local/lib/python2.7/site-packages/google/cloud/bigtable/client.py", line 34, in <module>
    from google.gax.utils import metrics
  File "/env/local/lib/python2.7/site-packages/google/gax/__init__.py", line 44, in <module>
    from google.rpc import code_pb2
  File "/env/local/lib/python2.7/site-packages/google/rpc/code_pb2.py", line 23, in <module>
    serialized_pb=_b('\n\x15google/rpc/code.proto\x12\ngoogle.rpc*\xb7\x02\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\r\n\tCANCELLED\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x12\x14\n\x10INVALID_ARGUMENT\x10\x03\x12\x15\n\x11\x44\x45\x41\x44LINE_EXCEEDED\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x06\x12\x15\n\x11PERMISSION_DENIED\x10\x07\x12\x13\n\x0fUNAUTHENTICATED\x10\x10\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x08\x12\x17\n\x13\x46\x41ILED_PRECONDITION\x10\t\x12\x0b\n\x07\x41\x42ORTED\x10\n\x12\x10\n\x0cOUT_OF_RANGE\x10\x0b\x12\x11\n\rUNIMPLEMENTED\x10\x0c\x12\x0c\n\x08INTERNAL\x10\r\x12\x0f\n\x0bUNAVAILABLE\x10\x0e\x12\r\n\tDATA_LOSS\x10\x0f\x42X\n\x0e\x63om.google.rpcB\tCodeProtoP\x01Z3google.golang.org/genproto/googleapis/rpc/code;code\xa2\x02\x03RPCb\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
[2019-03-05 17:55:53 +0000] [11] [INFO] Worker exiting (pid: 11)
[2019-03-05 17:55:53 +0000] [7] [INFO] Shutting down: Master
[2019-03-05 17:55:53 +0000] [7] [INFO] Reason: Worker failed to boot.
```

**Comment by critzo** [comment]
This is now resolved. Needed to update version of gunicorn in requirements file.
